AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bower_components/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
Documentation: # Disabling documentation cop
  Enabled: false
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
