default: &default
  adapter: mysql2
  host: localhost
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: db/restaurant_menu_dev

test:
  <<: *default
  database: db/restaurant_menu_test

production:
  <<: *default
  database: db/restaurant_menu_prod
